apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
  # annotations:
  #   konghq.com/plugins: key-auth
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
