apiVersion: v1
kind: Service
metadata:
  name: dgraph-service
  namespace: dgraph
  annotations:
    konghq.com/protocol: "grpc"
spec:
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080