apiVersion: v1
kind: Service
metadata:
  name: dgraph-grpc-service
  namespace: dgraph
  annotations:
    konghq.com/protocol: "grpc"
spec:
  ports:
  - name: grpc-port    
    protocol: TCP
    port: 9080
    targetPort: 9080