apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: kong
  annotations:
    konghq.com/plugins: key-auth
spec:
  selector:
    app: hello
  ports:
  - port: 80
    targetPort: 80
