apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: demo-user-traefik
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: kong
username: demo-user-traefik
credentials:
  - demo-user-key   
