apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: demo-user
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
username: demo-user
credentials:
  - demo-user-key   
