apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: keycloak-consumer
  namespace: dgraph
  annotations:
    kubernetes.io/ingress.class: "kong" 
username: keycloak-user
credentials:
  - keycloak-jwt-credential