apiVersion: v1
kind: Endpoints
metadata:
  name: dgraph-http-service   
  namespace: dgraph      
subsets:
  - addresses:
      - ip: 192.168.100.201
      - ip: 192.168.100.202
      - ip: 192.168.100.203
    ports:
    - name: http-port 
      port: 8080
      protocol: TCP