daemonize: false

#pcap_interface: any
pre_tag_map: /etc/pmacct/vm_ip.map
pcap_interfaces_map: /etc/pmacct/interfaces.map
pcap_filter: host 192.168.200.150 or host 192.168.200.151

pcap_ifindex: map

plugins: pgsql
sql_optimize_clauses: true
aggregate: tag, src_host, dst_host, proto, src_host_country, dst_host_country

geoipv2_file: /usr/share/GeoIP/GeoLite2-Country.mmdb

sql_table_version: 4

sql_host: <DB_HOST>
sql_port: <DB_PORT>
sql_db: <DB_NAME>
sql_table: <TABLE_NAME>
sql_user: <DB_USER>
sql_passwd: <DB_PASSWORD>


#sql_symlink_aggr: in_iface:agent_id
#pre_tag_filter: true
#pre_tag_filter[default_pgsql]: agent_id

sql_refresh_time: 1

sql_history: 1m
sql_history_roundoff: m

sql_dont_try_update: false
sql_use_copy: false